repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-yaml

        language_version: python3
-   repo: local
    hooks:
    -   id: pydocstyle
        name: Run pycodestyle
        entry: pycodestyle
        language: system
        files: \.py$

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        pass_filenames: false
